pipelines:
  default:
  - step:
      name: Build and Test
      image: node:lts-alpine3.19
      caches:
            - node
      script:
        - apk update && apk add nodejs npm
        - cd app
        - npm install
        - npm test