name: GitHub Actions Demo
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: node:lts-alpine3.19

    steps:
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test